using Avalonia;
using System;
using System.Collections.Generic;

namespace GlyphTV
{
    /// <summary>
    /// GlyphTV çoklu dil (Türkçe / İngilizce) yönetim sınıfı.
    /// Uygulama genelindeki metinlerin dinamik olarak güncellenmesini sağlar.
    /// </summary>
    public static class Localization
    {
        public static string CurrentLanguage { get; private set; } = "tr";

        public static System.Globalization.CultureInfo CurrentCulture => CurrentLanguage == "en" 
            ? new System.Globalization.CultureInfo("en-US") 
            : new System.Globalization.CultureInfo("tr-TR");

        public static event Action? LanguageChanged;

        private static readonly Dictionary<string, string> _tr = new()
        {
            // Ana Gezinme & Kenar Çubuğu
            ["Nav_Home"] = "Anasayfa",
            ["Nav_Live"] = "Canlı TV",
            ["Nav_Movies"] = "Filmler",
            ["Nav_Series"] = "Diziler",
            ["Nav_Favorites"] = "Favoriler",
            ["Nav_Categories"] = "Kategoriler",
            ["Nav_DragReorder"] = "⠿ ile sürükleyip sıralayın",
            ["Nav_SearchPlaceholder"] = "Kanal veya film ara...",
            ["Nav_Settings"] = "Ayarlar",
            ["Nav_Epg"] = "Yayın Akışı (EPG)",
            ["Nav_Back"] = "◀ Geri",

            // Sıralama
            ["Sort_AZ"] = "A-Z",
            ["Sort_ZA"] = "Z-A",
            ["Sort_New"] = "Yeni",
            ["Sort_AZ_Tooltip"] = "Alfabetik (A-Z) Sırala",
            ["Sort_ZA_Tooltip"] = "Ters Alfabetik (Z-A) Sırala",
            ["Sort_New_Tooltip"] = "Son Eklenenlere Göre Sırala",

            // Ortak Butonlar
            ["Btn_Play"] = "▶ Oynat",
            ["Btn_Resume"] = "▶ Devam Et",
            ["Btn_WatchNow"] = "▶ Hemen İzle",
            ["Hero_WatchNow"] = "Hemen İzle",
            ["Hero_Details"] = "Detaylar & Bölümler",
            ["Btn_Favorite"] = "Favori",
            ["Btn_Detail"] = "Detay",
            ["Btn_Details"] = "ⓘ Detaylar",
            ["Btn_Cancel"] = "İptal",
            ["Btn_Save"] = "Kaydet",
            ["Btn_Close"] = "Kapat",
            ["Btn_Edit"] = "Düzenle",
            ["Btn_Delete"] = "Sil",
            ["Btn_Refresh"] = "Yenile",
            ["Btn_RefreshUpper"] = "YENİLE",
            ["Btn_DeleteUpper"] = "SİL",
            ["Btn_Select"] = "Seç",
            ["Btn_Active"] = "Aktif",
            ["Btn_Reset"] = "Sıfırla",
            ["Btn_Season"] = "Sezon",
            ["Btn_Episode"] = "Bölüm",

            // Anasayfa
            ["Home_Featured"] = "Öne Çıkanlar",
            ["Home_FeaturedWeek"] = "Haftanın Popüler İçeriği",
            ["Home_ResumeTitle"] = "Devam Et",
            ["Home_ResumeEmpty"] = "Henüz yarıda bırakılan bir film veya dizi bulunmuyor.",
            ["Home_FilterAll"] = "Tümü",
            ["Home_FilterMovies"] = "Filmler",
            ["Home_FilterSeries"] = "Diziler",
            ["Home_PopularTitle"] = "Popüler İçerikler",
            ["Home_PopularSubtitle"] = "TMDb verilerine göre bu hafta trend olan yapımlar",
            ["Loc_ResumeRemove"] = "Devam Et Listesinden Kaldır",
            ["Loc_ResumeRemoveTooltip"] = "Devam Et listesinden kaldır",

            // Favoriler
            ["Fav_LiveChannels"] = "Favori Canlı Kanallar",
            ["Fav_Movies"] = "Favori Filmler",
            ["Fav_Series"] = "Favori Diziler",
            ["Fav_EmptyLive"] = "Favori kanalınız bulunmuyor.",
            ["Fav_EmptyMovies"] = "Favori filminiz bulunmuyor.",
            ["Fav_EmptySeries"] = "Favori diziniz bulunmuyor.",

            // Ayarlar Modalı
            ["Settings_Title"] = "Ayarlar",
            ["Settings_Subtitle"] = "Uygulama tercihleri, oynatıcı ve IPTV kaynak yönetimi",
            ["Settings_CloseTooltip"] = "Kapat (Esc)",
            ["Settings_NavSources"] = "Kaynaklar",
            ["Settings_NavSourcesSub"] = "M3U & Xtream listeleri",
            ["Settings_NavAppearance"] = "Genel & Görünüm",
            ["Settings_NavAppearanceSub"] = "Tema, dil & motor",
            ["Settings_NavData"] = "Veri & Depolama",
            ["Settings_NavDataSub"] = "Geçmiş, önbellek ve sıfırlama",
            ["Settings_NavShortcuts"] = "Kısayollar",
            ["Settings_NavShortcutsSub"] = "Klavye & fare tuşları",
            ["Settings_NavAbout"] = "Hakkında",
            ["Settings_NavAboutSub"] = "Sürüm bilgisi & topluluk",

            // Ayarlar: Kaynaklar
            ["Settings_SourcesTitle"] = "IPTV Kaynakları",
            ["Settings_SourcesSubtitle"] = "M3U oynatma listelerinizi veya Xtream hesaplarınızı yönetin.",
            ["Settings_AddSourceBtn"] = "+ Yeni Kaynak Ekle",
            ["Settings_SavedSources"] = "Kayıtlı Oynatma Listeleri",
            ["Settings_SelectSourceTooltip"] = "Kaynağı Seç / Aktif Et",
            ["Settings_RefreshSourceTooltip"] = "Kaynağı Yenile",
            ["Settings_DeleteSourceTooltip"] = "Kaynağı Sil",

            // Ayarlar: Genel & Görünüm
            ["Settings_AppearanceTitle"] = "Genel & Görünüm Ayarları",
            ["Settings_AppearanceSubtitle"] = "Arayüz dili, teması, başlangıç tercihleri ve oynatma motorunu yapılandırın.",
            ["Settings_LanguageTitle"] = "Dil Seçimi",
            ["Settings_LanguageSubtitle"] = "Uygulama arayüz dilini belirleyin (Türkçe / English)",
            ["Settings_ThemeTitle"] = "Tema Seçimi",
            ["Settings_ThemeSubtitle"] = "Sistem temasına uyun veya koyu/açık temayı zorlayın",
            ["Settings_ThemeSystem"] = "SİSTEM",
            ["Settings_ThemeLight"] = "AÇIK",
            ["Settings_ThemeDark"] = "KOYU",
            ["Settings_AutoRefreshTitle"] = "Başlangıçta Otomatik Yenileme",
            ["Settings_AutoRefreshSubtitle"] = "Uygulama her açıldığında aktif IPTV listesini sunucudan otomatik günceller",
            ["Settings_CheckUpdatesTitle"] = "Açılışta Güncellemeleri Denetle",
            ["Settings_CheckUpdatesSubtitle"] = "Uygulama başladığında arka planda sessizce yeni sürüm olup olmadığını kontrol eder",
            ["Settings_PlayerEngineTitle"] = "Oynatıcı Motoru",
            ["Settings_PlayerEngineSubtitle"] = "VLC (LibVLCSharp) veya mpv (libmpv) motoru",
            ["Settings_ToggleOn"] = "AÇIK",
            ["Settings_ToggleOff"] = "KAPALI",

            // Ayarlar: Veri & Depolama
            ["Settings_DataTitle"] = "Veri & Depolama Yönetimi",
            ["Settings_DataSubtitle"] = "İzleme geçmişi, disk ve RAM önbelleği ile uygulama sıfırlama işlemleri.",
            ["Settings_ClearHistoryTitle"] = "İzleme Geçmişini Temizle",
            ["Settings_ClearHistorySubtitle"] = "Kaldığınız yerden devam etme pozisyonlarını ve izleme geçmişini siler",
            ["Settings_ClearHistoryBtn"] = "GEÇMİŞİ TEMİZLE",
            ["Settings_ClearCacheTitle"] = "Logo & Görsel Önbelleğini Temizle",
            ["Settings_ClearCacheSubtitle"] = "İndirilen kanal logolarını ve TMDb poster önbelleğini temizler",
            ["Settings_ClearCacheBtn"] = "ÖNBELLEĞİ TEMİZLE",
            ["Settings_ResetAppTitle"] = "Fabrika Ayarlarına Sıfırla",
            ["Settings_ResetAppSubtitle"] = "Tüm uygulama ayarlarını ve tercihleri varsayılan değerlere döndürür",
            ["Settings_ResetAppBtn"] = "UYGULAMAYI SIFIRLA",

            // Ayarlar: Kısayollar
            ["Settings_ShortcutsTitle"] = "Klavye & Fare Kısayolları",
            ["Settings_ShortcutsSubtitle"] = "Hızlı gezinme, medya kontrolü, resim modları ve ses/altyazı senkronizasyonu için kullanabileceğiniz tüm kısayollar.",
            ["Kbd_PlaybackControls"] = "Oynatma & Medya Kontrolleri",
            ["Kbd_PlayPause"] = "Oynat / Duraklat",
            ["Kbd_PlayPauseKeys"] = "Space  /  Sol Tık",
            ["Kbd_Fullscreen"] = "Tam Ekran Aç / Kapat",
            ["Kbd_FullscreenKeys"] = "F  /  Çift Tık",
            ["Kbd_Pip"] = "Resim İçinde Resim (PiP) Modu",
            ["Kbd_Mute"] = "Sesi Aç / Kapat (Mute)",
            ["Kbd_Seek"] = "10 Saniye Geri / İleri Sar (Film & Dizi)",
            ["Kbd_VolumeChannel"] = "Ses Seviyesi (Film/Dizi) / Kanal Değiştir (Canlı)",
            ["Kbd_Search"] = "Kanal ve İçerik Arama",
            ["Kbd_Close"] = "Pencereleri, PiP ve Modalleri Kapat",
            ["Kbd_PictureModes"] = "Görüntü ve Resim Modları",
            ["Kbd_PresetNatural"] = "Resim Modu: Doğal (Nötr / Standart Renkler)",
            ["Kbd_PresetVivid"] = "Resim Modu: Canlı (Yüksek Doygunluk & Dinamik Kontrast)",
            ["Kbd_PresetSports"] = "Resim Modu: Spor (Akıcı Hareket & Canlı Saha/Zemin Tonları)",
            ["Kbd_PresetCinema"] = "Resim Modu: Sinema (Sıcak Film Tonları & Derin Siyahlar)",
            ["Kbd_SyncControls"] = "Ses ve Altyazı Senkronizasyonu",
            ["Kbd_AudioAdvance"] = "Sesi İlerlet / Hızlı İlerlet (-50 ms / -500 ms)",
            ["Kbd_AudioDelay"] = "Sesi Geciktir / Hızlı Geciktir (+50 ms / +500 ms)",
            ["Kbd_AudioReset"] = "Ses Senkronunu Sıfırla (0 ms)",
            ["Kbd_SubAdvance"] = "Altyazıyı Erken / Çok Erken Ver (-50 ms / -500 ms)",
            ["Kbd_SubDelay"] = "Altyazıyı Geciktir / Çok Geciktir (+50 ms / +500 ms)",
            ["Kbd_SubReset"] = "Altyazı Senkronunu Sıfırla (0 ms)",

            // Ayarlar: Hakkında
            ["Settings_AboutTitle"] = "Hakkında & Topluluk",
            ["Settings_AboutSubtitle"] = "GlyphTV geliştirici bilgileri, lisans ve topluluk bağlantıları.",
            ["Settings_Version"] = "Sürüm",
            ["Settings_Developer"] = "Geliştirici",
            ["Settings_Copyright"] = "Telif",
            ["Settings_AppDesc"] = "Modern, hızlı ve minimal IPTV oynatıcı. Avalonia UI, LibVLCSharp ve libmpv ile güçlendirilmiştir.",
            ["Settings_UpdateTitle"] = "Yazılım Güncellemesi",
            ["Settings_VersionUpToDate"] = "Sürüm Güncel",
            ["Settings_NewVersionAvailable"] = "Yeni Sürüm Mevcut",
            ["Settings_AutoCheckActive"] = "Otomatik denetim aktif",
            ["Settings_CheckNow"] = "Kontrol Et",
            ["Settings_Checking"] = "Denetleniyor...",
            ["Settings_GithubTitle"] = "GitHub Deposu",
            ["Settings_GithubSubtitle"] = "Projeyi yıldızlayın veya katkıda bulunun",

            // Modallar: Kaynak Ekle / Düzenle
            ["SourceModal_TitleAdd"] = "Yeni Kaynak Ekle",
            ["SourceModal_TitleEdit"] = "Kaynağı Düzenle",
            ["SourceModal_Name"] = "Kaynak Adı",
            ["SourceModal_NamePlaceholder"] = "Örn: Ana Kaynak",
            ["SourceModal_Type"] = "Kaynak Tipi",
            ["SourceModal_TypeXtreamDesc"] = "sağlayıcınızın verdiği sunucu adresi + kullanıcı adı + şifre (bir Xtream/Xtreme Codes panel girişi).",
            ["SourceModal_TypeM3uDesc"] = "bilgisayarınızdaki bir .m3u/.m3u8 dosyası.",
            ["SourceModal_TypeLinkDesc"] = "aynı listenin bir internet adresi (URL).",
            ["SourceModal_DragDrop"] = "M3U dosyasını buraya sürükleyin",
            ["SourceModal_OrClick"] = "veya tıklayın",
            ["SourceModal_OrUrl"] = "veya URL ile ekleyin",
            ["SourceModal_UrlPlaceholder"] = "http:// veya https:// ile başlayan link",
            ["SourceModal_EpgUrl"] = "Yayın Akışı (EPG) linki — opsiyonel",
            ["SourceModal_EpgPlaceholder"] = "ör: http://saglayici.com/xmltv.php veya .../epg.xml.gz",
            ["SourceModal_EpgHelp"] = "Sağlayıcınız genelde bunu 'EPG URL' veya 'XMLTV URL' adıyla panelinde/duyurularında paylaşır. Bulamıyorsanız boş bırakın; kaynağı EPG'siz de kullanabilir, sonradan kaynağı silip bu linkle yeniden ekleyebilirsiniz.",
            ["SourceModal_XtreamUrlPlaceholder"] = "Sunucu URL (http://...)",
            ["SourceModal_XtreamUserPlaceholder"] = "Kullanıcı Adı",
            ["SourceModal_XtreamPassPlaceholder"] = "Şifre",
            ["SourceModal_XtreamHelp"] = "Yayın Akışı (EPG) bu tür kaynaklarda otomatik gelir — sunucunuz xmltv.php destekliyorsa ekstra bir şey girmenize gerek yok.",
            ["SourceModal_XtreamEpgUrl"] = "Yayın Akışı (EPG) linki — opsiyonel",
            ["SourceModal_XtreamEpgPlaceholder"] = "ör: http://.../epg.xml.gz (harici XMLTV linki)",
            ["SourceModal_XtreamEpgHelp"] = "Sunucunuz xmltv.php desteklemiyorsa harici bir XMLTV linki (örn. .../epg.xml.gz) girebilirsiniz.",
            ["SourceModal_AddBtn"] = "Kaynak Ekle",
            ["SourceModal_SaveBtn"] = "Değişiklikleri Kaydet",

            // Modallar: EPG
            ["Epg_Title"] = "🗓️ Yayın Akışı (EPG)",
            ["Epg_Timeline_Title"] = "🗓️ Yayın Akışı",
            ["Epg_RefreshTooltip"] = "EPG'yi yeniden indir",
            ["Epg_EditUrlTooltip"] = "EPG linkini ayarla / değiştir",
            ["Epg_EditUrlTitle"] = "EPG / XMLTV Linkini Düzenle",
            ["Epg_EditUrlSub"] = "Bu oynatma listesi için harici bir XMLTV / EPG linki (örn. http://.../epg.xml.gz) belirleyin.",
            ["Epg_EditUrlPlaceholder"] = "http://.../epg.xml.gz veya xmltv linki",
            ["Epg_EditUrlSaveBtn"] = "Kaydet ve Yenile",
            ["Epg_EditUrlCancelBtn"] = "İptal",
            ["Epg_StatusChecking"] = "EPG kontrol ediliyor...",
            ["Epg_StatusDownloading"] = "EPG indiriliyor...",
            ["Epg_StatusFailed"] = "EPG indirilemedi — bağlantıyı veya EPG linkini kontrol edin.",
            ["Epg_Status404"] = "Sunucuda xmltv.php bulunamadı (404). Lütfen 🔗 butonundan harici bir EPG linki tanımlayın.",
            ["Epg_StatusUpdated"] = "EPG güncellendi · {0} program · {1}",
            ["Epg_StatusCached"] = "EPG güncel · {0} tarihinde önbellekten yüklendi",
            ["Epg_StatusCachedFallback"] = "İndirme başarısız oldu · {0} tarihli önbellek gösteriliyor",
            ["Epg_StatusEmpty"] = "EPG sunucudan boş döndü.",
            ["Epg_StatusNoLink"] = "Bu kaynak için EPG linki tanımlı değil. Yukarıdaki 🔗 butonuna basarak bir EPG linki ekleyebilirsiniz.",
            ["Epg_AllCategories"] = "Tüm Kategoriler",
            ["Epg_SearchPlaceholder"] = "Kanal Ara...",
            ["Epg_PrevDay"] = "◀ Önceki Gün",
            ["Epg_NextDay"] = "Sonraki Gün ▶",
            ["Epg_Now"] = "Şimdi",
            ["Epg_NoGuide"] = "Yayın Akışı Yok",

            // Modallar: VOD / Dizi Detayı
            ["VodInfo_Play"] = "▶ Oynat",
            ["VodInfo_Resume"] = "▶ Kaldığı Yerden Devam Et",
            ["VodInfo_AddFav"] = "Favorilere Ekle",
            ["VodInfo_RemoveFav"] = "Favorilerden Çıkar",
            ["VodInfo_InFavorites"] = "Favorilerde",
            ["VodInfo_Favorite"] = "Favori",
            ["VodInfo_MovieDetails"] = "Film Detayları",
            ["VodInfo_SeriesDetails"] = "Dizi Detayları",
            ["VodInfo_Director"] = "Yönetmen:",
            ["VodInfo_Cast"] = "Oyuncular:",
            ["VodInfo_Genre"] = "Tür:",
            ["VodInfo_Duration"] = "Süre:",
            ["VodInfo_ReleaseDate"] = "Çıkış Tarihi:",
            ["VodInfo_Rating"] = "Puan:",
            ["VodInfo_SeasonsEpisodes"] = "Sezonlar & Bölümler",

            // Modallar: Güncelleme
            ["Update_Title"] = "GlyphTV Güncellemesi Mevcut!",
            ["Update_Current"] = "Mevcut: v{0}",
            ["Update_WhatsNew"] = "Neler Yeni?",
            ["Update_BtnUpdate"] = "Şimdi Güncelle",
            ["Update_BtnLater"] = "Daha Sonra",
            ["Update_DownloadHelp"] = "İndirme tamamlandığında GlyphTV otomatik güncellenip yeniden başlayacaktır.",
            ["Update_Downloading"] = "İndiriliyor... %{0}",

            // Oynatıcı Kontrolleri & Player Overlay
            ["Player_Live"] = "CANLI",
            ["Player_AudioTrack"] = "Ses Dili",
            ["Player_Channels"] = "Kanallar",
            ["Player_AspectRatio"] = "En:Boy Oranı",
            ["Player_Subtitles"] = "Altyazı / Dil",
            ["Player_Enhanced"] = "Enhanced",
            ["Player_PlayPauseTooltip"] = "Oynat / Duraklat (Space)",
            ["Player_RewindTooltip"] = "10s Geri (←)",
            ["Player_ForwardTooltip"] = "10s İleri (→)",
            ["Player_SpeedTooltip"] = "Oynatma Hızı",
            ["Player_MuteTooltip"] = "Sesi Kapat / Aç (M)",
            ["Player_PipTooltip"] = "PiP Modu (Shift+T)",
            ["Player_FullscreenTooltip"] = "Tam Ekran (F)",
            ["Player_AudioSync"] = "Ses Senkronizasyonu",
            ["Player_AudioSyncReset"] = "Ses Senkronunu Sıfırla (0 ms)",
            ["Player_SubtitleSync"] = "Altyazı Senkronizasyonu",
            ["Player_SubtitleSyncReset"] = "Senkronu Sıfırla (0 ms)",
            ["Player_AspectAuto"] = "Otomatik",
            ["Player_AspectOriginal"] = "Orijinal",
            ["Player_Enhanced_Title"] = "ENHANCED",
            ["Player_Enhanced_Reset"] = "Sıfırla",
            ["Player_ShaderTitle"] = "GÖRÜNTÜ İYİLEŞTİRME & SHADER",
            ["Player_ShaderOff"] = "Kapalı",
            ["Player_ShaderDesc"] = "AMD FidelityFX algoritmaları ile yayını netleştirir veya 4K ölçekler.",
            ["Player_FastZapTitle"] = "CANLI TV KANAL GEÇİŞİ",
            ["Player_FastZapUltra"] = "⚡ Ultra Hızlı (200ms)",
            ["Player_FastZapStd"] = "Standart (Kararlı)",
            ["Player_FastZapDesc"] = "Canlı TV geçişlerinde tamponu sıfırlayarak kanal açılışını anında görüntüye indirir.",
            ["Player_AudioEnhTitle"] = "AKILLI SES İŞLEME",
            ["Player_AudioEnhOff"] = "Kapalı",
            ["Player_AudioEnhLoudnorm"] = "EBU R128 Dengeleme",
            ["Player_AudioEnhNight"] = "Gece Modu (Kompresör)",
            ["Player_AudioEnhDesc"] = "Kanal geçişlerindeki ani ses patlamalarını önler veya gece kısık sesle net diyalog sağlar.",
            ["Player_HwTitle"] = "DONANIM ÇÖZÜMLEME",
            ["Player_HwDesc"] = "Ekran kartınızı (GPU) video çözümlemede kullanarak işlemci (CPU) yükünü sıfıra indirir.",
            ["Player_DeintTitle"] = "TARAMASIZLAŞTIRMA (DEINTERLACE)",
            ["Player_DeintOn"] = "Açık",
            ["Player_DeintOff"] = "Kapalı",
            ["Player_DeintDesc"] = "1080i / 576i yayınlardaki tarama çizgilerini gidererek görüntüyü akıcı progressive'e dönüştürür.",
            ["Player_PresetTitle"] = "RESİM MODU",
            ["Player_PresetNatural"] = "Doğal",
            ["Player_PresetVivid"] = "Canlı",
            ["Player_PresetSports"] = "Spor",
            ["Player_PresetCinema"] = "Sinema",
            ["Player_PresetCustom"] = "Özel",
            ["Player_EqualizerTitle"] = "İNCE GÖRÜNTÜ AYARLARI",
            ["Player_Brightness"] = "Parlaklık",
            ["Player_Contrast"] = "Kontrast",
            ["Player_Saturation"] = "Doygunluk",
            ["Player_Gamma"] = "Gama",
            ["Player_EqReset"] = "Görüntü Ayarlarını Sıfırla (0)",

            // Bildirimler (Toasts)
            ["Toast_RemovedFromResume"] = "'{0}' devam et listesinden kaldırıldı.",
            ["Toast_AllHistoryCleared"] = "İzleme geçmişi temizlendi.",
            ["Toast_SourceDeleted"] = "Kaynak silindi.",
            ["Toast_CacheCleared"] = "Önbellek temizlendi.",
            ["Toast_AppReset"] = "Tüm ayarlar sıfırlandı.",
            ["Toast_StartingOver"] = "Baştan başlatılıyor...",
            ["Toast_ResumingAt"] = "{0} konumundan devam ediliyor",
            ["Toast_AddedToFav"] = "Favorilere eklendi",
            ["Toast_RemovedFromFav"] = "Favorilerden çıkarıldı",
            ["Toast_SeriesAddedToFav"] = "Dizi favorilere eklendi",
            ["Toast_SeriesRemovedFromFav"] = "Dizi favorilerden çıkarıldı",
            ["Toast_SourceLoaded"] = "'{0}' kaynağı aktifleştirildi.",
            ["Toast_SourceLoading"] = "'{0}' yükleniyor...",
            ["Toast_LangChanged"] = "Uygulama dili Türkçe olarak ayarlandı.",
            ["Toast_ContentNotAvailableInSource"] = "Bu içerik aktif olan kaynakta mevcut değil.",
            ["Toast_ContentNotInPlaylist"] = "Bu içerik henüz oynatma listenizde bulunmuyor.",
            ["Toast_LoadDetailsError"] = "Detay bilgisi yüklenemedi."
        };

        private static readonly Dictionary<string, string> _en = new()
        {
            // Main Navigation & Sidebar
            ["Nav_Home"] = "Home",
            ["Nav_Live"] = "Live TV",
            ["Nav_Movies"] = "Movies",
            ["Nav_Series"] = "Series",
            ["Nav_Favorites"] = "Favorites",
            ["Nav_Categories"] = "Categories",
            ["Nav_DragReorder"] = "Drag ⠿ to reorder",
            ["Nav_SearchPlaceholder"] = "Search channels or movies...",
            ["Nav_Settings"] = "Settings",
            ["Nav_Epg"] = "TV Guide (EPG)",
            ["Nav_Back"] = "◀ Back",

            // Sorting
            ["Sort_AZ"] = "A-Z",
            ["Sort_ZA"] = "Z-A",
            ["Sort_New"] = "New",
            ["Sort_AZ_Tooltip"] = "Sort Alphabetically (A-Z)",
            ["Sort_ZA_Tooltip"] = "Sort Reverse Alphabetically (Z-A)",
            ["Sort_New_Tooltip"] = "Sort by Recently Added",

            // Common Buttons
            ["Btn_Play"] = "▶ Play",
            ["Btn_Resume"] = "▶ Resume",
            ["Btn_WatchNow"] = "▶ Watch Now",
            ["Hero_WatchNow"] = "Watch Now",
            ["Hero_Details"] = "Details & Episodes",
            ["Btn_Favorite"] = "Favorite",
            ["Btn_Detail"] = "Detail",
            ["Btn_Details"] = "ⓘ Details",
            ["Btn_Cancel"] = "Cancel",
            ["Btn_Save"] = "Save",
            ["Btn_Close"] = "Close",
            ["Btn_Edit"] = "Edit",
            ["Btn_Delete"] = "Delete",
            ["Btn_Refresh"] = "Refresh",
            ["Btn_RefreshUpper"] = "REFRESH",
            ["Btn_DeleteUpper"] = "DELETE",
            ["Btn_Select"] = "Select",
            ["Btn_Active"] = "Active",
            ["Btn_Reset"] = "Reset",
            ["Btn_Season"] = "Season",
            ["Btn_Episode"] = "Episode",

            // Home Page
            ["Home_Featured"] = "Featured",
            ["Home_FeaturedWeek"] = "Popular This Week",
            ["Home_ResumeTitle"] = "Continue Watching",
            ["Home_ResumeEmpty"] = "No unfinished movies or series found.",
            ["Home_FilterAll"] = "All",
            ["Home_FilterMovies"] = "Movies",
            ["Home_FilterSeries"] = "Series",
            ["Home_PopularTitle"] = "Popular Content",
            ["Home_PopularSubtitle"] = "Trending titles this week based on TMDb",
            ["Loc_ResumeRemove"] = "Remove from Continue Watching",
            ["Loc_ResumeRemoveTooltip"] = "Remove from Continue Watching",

            // Favorites
            ["Fav_LiveChannels"] = "Favorite Live Channels",
            ["Fav_Movies"] = "Favorite Movies",
            ["Fav_Series"] = "Favorite Series",
            ["Fav_EmptyLive"] = "No favorite channels found.",
            ["Fav_EmptyMovies"] = "No favorite movies found.",
            ["Fav_EmptySeries"] = "No favorite series found.",

            // Settings Modal
            ["Settings_Title"] = "Settings",
            ["Settings_Subtitle"] = "Application preferences, player and IPTV source management",
            ["Settings_CloseTooltip"] = "Close (Esc)",
            ["Settings_NavSources"] = "Sources",
            ["Settings_NavSourcesSub"] = "M3U & Xtream playlists",
            ["Settings_NavAppearance"] = "General & Appearance",
            ["Settings_NavAppearanceSub"] = "Theme, language & engine",
            ["Settings_NavData"] = "Data & Storage",
            ["Settings_NavDataSub"] = "History, cache and reset",
            ["Settings_NavShortcuts"] = "Shortcuts",
            ["Settings_NavShortcutsSub"] = "Keyboard & mouse shortcuts",
            ["Settings_NavAbout"] = "About",
            ["Settings_NavAboutSub"] = "Version info & community",

            // Settings: Sources
            ["Settings_SourcesTitle"] = "IPTV Sources",
            ["Settings_SourcesSubtitle"] = "Manage your M3U playlists or Xtream accounts.",
            ["Settings_AddSourceBtn"] = "+ Add New Source",
            ["Settings_SavedSources"] = "Saved Playlists",
            ["Settings_SelectSourceTooltip"] = "Select / Activate Source",
            ["Settings_RefreshSourceTooltip"] = "Refresh Source",
            ["Settings_DeleteSourceTooltip"] = "Delete Source",

            // Settings: General & Appearance
            ["Settings_AppearanceTitle"] = "General & Appearance Settings",
            ["Settings_AppearanceSubtitle"] = "Configure interface language, theme, startup preferences and player engine.",
            ["Settings_LanguageTitle"] = "Language Selection",
            ["Settings_LanguageSubtitle"] = "Select application interface language (Türkçe / English)",
            ["Settings_ThemeTitle"] = "Theme Selection",
            ["Settings_ThemeSubtitle"] = "Follow system theme or force light/dark mode",
            ["Settings_ThemeSystem"] = "SYSTEM",
            ["Settings_ThemeLight"] = "LIGHT",
            ["Settings_ThemeDark"] = "DARK",
            ["Settings_AutoRefreshTitle"] = "Auto Refresh on Startup",
            ["Settings_AutoRefreshSubtitle"] = "Automatically updates active IPTV playlist from server when app starts",
            ["Settings_CheckUpdatesTitle"] = "Check for Updates on Startup",
            ["Settings_CheckUpdatesSubtitle"] = "Silently checks for new releases in background when app launches",
            ["Settings_PlayerEngineTitle"] = "Player Engine",
            ["Settings_PlayerEngineSubtitle"] = "VLC (LibVLCSharp) or mpv (libmpv) engine",
            ["Settings_ToggleOn"] = "ON",
            ["Settings_ToggleOff"] = "OFF",

            // Settings: Data & Storage
            ["Settings_DataTitle"] = "Data & Storage Management",
            ["Settings_DataSubtitle"] = "Watch history, disk & RAM cache, and application reset operations.",
            ["Settings_ClearHistoryTitle"] = "Clear Watch History",
            ["Settings_ClearHistorySubtitle"] = "Deletes resume positions and watch history",
            ["Settings_ClearHistoryBtn"] = "CLEAR HISTORY",
            ["Settings_ClearCacheTitle"] = "Clear Logo & Image Cache",
            ["Settings_ClearCacheSubtitle"] = "Clears downloaded channel logos and TMDb poster cache",
            ["Settings_ClearCacheBtn"] = "CLEAR CACHE",
            ["Settings_ResetAppTitle"] = "Factory Reset",
            ["Settings_ResetAppSubtitle"] = "Restores all application settings and preferences to default values",
            ["Settings_ResetAppBtn"] = "RESET APP",

            // Settings: Shortcuts
            ["Settings_ShortcutsTitle"] = "Keyboard & Mouse Shortcuts",
            ["Settings_ShortcutsSubtitle"] = "All shortcuts for quick navigation, media control, picture presets and audio/subtitle sync.",
            ["Kbd_PlaybackControls"] = "Playback & Media Controls",
            ["Kbd_PlayPause"] = "Play / Pause",
            ["Kbd_PlayPauseKeys"] = "Space  /  Left Click",
            ["Kbd_Fullscreen"] = "Toggle Fullscreen",
            ["Kbd_FullscreenKeys"] = "F  /  Double Click",
            ["Kbd_Pip"] = "Picture-in-Picture (PiP) Mode",
            ["Kbd_Mute"] = "Mute / Unmute",
            ["Kbd_Seek"] = "Seek 10s Backward / Forward (Movie & Series)",
            ["Kbd_VolumeChannel"] = "Volume (Movie/Series) / Switch Channel (Live)",
            ["Kbd_Search"] = "Channel & Content Search",
            ["Kbd_Close"] = "Close Windows, PiP and Modals",
            ["Kbd_PictureModes"] = "Video & Picture Presets",
            ["Kbd_PresetNatural"] = "Picture Preset: Natural (Neutral / Standard Colors)",
            ["Kbd_PresetVivid"] = "Picture Preset: Vivid (High Saturation & Dynamic Contrast)",
            ["Kbd_PresetSports"] = "Picture Preset: Sports (Smooth Motion & Vibrant Pitch Colors)",
            ["Kbd_PresetCinema"] = "Picture Preset: Cinema (Warm Film Tones & Deep Blacks)",
            ["Kbd_SyncControls"] = "Audio & Subtitle Sync",
            ["Kbd_AudioAdvance"] = "Advance Audio / Fast Advance (-50 ms / -500 ms)",
            ["Kbd_AudioDelay"] = "Delay Audio / Fast Delay (+50 ms / +500 ms)",
            ["Kbd_AudioReset"] = "Reset Audio Sync (0 ms)",
            ["Kbd_SubAdvance"] = "Advance Subtitle / Fast Advance (-50 ms / -500 ms)",
            ["Kbd_SubDelay"] = "Delay Subtitle / Fast Delay (+50 ms / +500 ms)",
            ["Kbd_SubReset"] = "Reset Subtitle Sync (0 ms)",

            // Settings: About
            ["Settings_AboutTitle"] = "About & Community",
            ["Settings_AboutSubtitle"] = "GlyphTV developer information, license and community links.",
            ["Settings_Version"] = "Version",
            ["Settings_Developer"] = "Developer",
            ["Settings_Copyright"] = "Copyright",
            ["Settings_AppDesc"] = "Modern, fast and minimal IPTV player. Powered by Avalonia UI, LibVLCSharp and libmpv.",
            ["Settings_UpdateTitle"] = "Software Update",
            ["Settings_VersionUpToDate"] = "Up to date",
            ["Settings_NewVersionAvailable"] = "New Version Available",
            ["Settings_AutoCheckActive"] = "Automatic check active",
            ["Settings_CheckNow"] = "Check Now",
            ["Settings_Checking"] = "Checking...",
            ["Settings_GithubTitle"] = "GitHub Repository",
            ["Settings_GithubSubtitle"] = "Star the project or contribute",

            // Modals: Add / Edit Source
            ["SourceModal_TitleAdd"] = "Add New Source",
            ["SourceModal_TitleEdit"] = "Edit Source",
            ["SourceModal_Name"] = "Source Name",
            ["SourceModal_NamePlaceholder"] = "e.g.: Main Source",
            ["SourceModal_Type"] = "Source Type",
            ["SourceModal_TypeXtreamDesc"] = "server URL + username + password provided by your provider (Xtream Codes API).",
            ["SourceModal_TypeM3uDesc"] = "a local .m3u/.m3u8 file on your computer.",
            ["SourceModal_TypeLinkDesc"] = "an internet URL of the same playlist.",
            ["SourceModal_DragDrop"] = "Drag M3U file here",
            ["SourceModal_OrClick"] = "or click to browse",
            ["SourceModal_OrUrl"] = "or add via URL",
            ["SourceModal_UrlPlaceholder"] = "URL starting with http:// or https://",
            ["SourceModal_EpgUrl"] = "TV Guide (EPG) link — optional",
            ["SourceModal_EpgPlaceholder"] = "e.g.: http://provider.com/xmltv.php or .../epg.xml.gz",
            ["SourceModal_EpgHelp"] = "Your provider usually shares this as 'EPG URL' or 'XMLTV URL'. Leave empty if not available; you can add it later.",
            ["SourceModal_XtreamUrlPlaceholder"] = "Server URL (http://...)",
            ["SourceModal_XtreamUserPlaceholder"] = "Username",
            ["SourceModal_XtreamPassPlaceholder"] = "Password",
            ["SourceModal_XtreamHelp"] = "TV Guide (EPG) is automatically retrieved for Xtream sources if supported by server.",
            ["SourceModal_XtreamEpgUrl"] = "TV Guide (EPG) URL — optional",
            ["SourceModal_XtreamEpgPlaceholder"] = "e.g. http://.../epg.xml.gz (external XMLTV link)",
            ["SourceModal_XtreamEpgHelp"] = "If your server does not support xmltv.php, you can enter an external XMLTV URL.",
            ["SourceModal_AddBtn"] = "Add Source",
            ["SourceModal_SaveBtn"] = "Save Changes",

            // Modals: EPG
            ["Epg_Title"] = "🗓️ TV Guide (EPG)",
            ["Epg_Timeline_Title"] = "🗓️ TV Guide",
            ["Epg_RefreshTooltip"] = "Refresh EPG",
            ["Epg_EditUrlTooltip"] = "Set / Edit EPG link",
            ["Epg_EditUrlTitle"] = "Edit EPG / XMLTV Link",
            ["Epg_EditUrlSub"] = "Set an external XMLTV / EPG URL for this playlist (e.g. http://.../epg.xml.gz).",
            ["Epg_EditUrlPlaceholder"] = "http://.../epg.xml.gz or xmltv link",
            ["Epg_EditUrlSaveBtn"] = "Save & Refresh",
            ["Epg_EditUrlCancelBtn"] = "Cancel",
            ["Epg_StatusChecking"] = "Checking EPG...",
            ["Epg_StatusDownloading"] = "Downloading EPG...",
            ["Epg_StatusFailed"] = "Could not download EPG — check your connection or EPG URL.",
            ["Epg_Status404"] = "xmltv.php not found on server (404). Please set an external EPG URL via 🔗 button.",
            ["Epg_StatusUpdated"] = "EPG updated · {0} programs · {1}",
            ["Epg_StatusCached"] = "EPG up to date · Loaded from cache at {0}",
            ["Epg_StatusCachedFallback"] = "Download failed · Showing cache from {0}",
            ["Epg_StatusEmpty"] = "EPG returned empty from server.",
            ["Epg_StatusNoLink"] = "No EPG URL configured for this source. Click 🔗 above to add an EPG link.",
            ["Epg_AllCategories"] = "All Categories",
            ["Epg_SearchPlaceholder"] = "Search Channels...",
            ["Epg_PrevDay"] = "◀ Previous Day",
            ["Epg_NextDay"] = "Next Day ▶",
            ["Epg_Now"] = "Now",
            ["Epg_NoGuide"] = "No Guide Information",

            // Modals: VOD / Series Detail
            ["VodInfo_Play"] = "▶ Play",
            ["VodInfo_Resume"] = "▶ Resume from last position",
            ["VodInfo_AddFav"] = "Add to Favorites",
            ["VodInfo_RemoveFav"] = "Remove from Favorites",
            ["VodInfo_InFavorites"] = "In Favorites",
            ["VodInfo_Favorite"] = "Favorite",
            ["VodInfo_MovieDetails"] = "Movie Details",
            ["VodInfo_SeriesDetails"] = "Series Details",
            ["VodInfo_Director"] = "Director:",
            ["VodInfo_Cast"] = "Cast:",
            ["VodInfo_Genre"] = "Genre:",
            ["VodInfo_Duration"] = "Duration:",
            ["VodInfo_ReleaseDate"] = "Release Date:",
            ["VodInfo_Rating"] = "Rating:",
            ["VodInfo_SeasonsEpisodes"] = "Seasons & Episodes",

            // Modals: Update
            ["Update_Title"] = "GlyphTV Update Available!",
            ["Update_Current"] = "Current: v{0}",
            ["Update_WhatsNew"] = "What's New?",
            ["Update_BtnUpdate"] = "Update Now",
            ["Update_BtnLater"] = "Later",
            ["Update_DownloadHelp"] = "GlyphTV will update and restart automatically when the download completes.",
            ["Update_Downloading"] = "Downloading... {0}%",

            // Player Controls & Player Overlay
            ["Player_Live"] = "LIVE",
            ["Player_AudioTrack"] = "Audio Track",
            ["Player_Channels"] = "Channels",
            ["Player_AspectRatio"] = "Aspect Ratio",
            ["Player_Subtitles"] = "Subtitles / Language",
            ["Player_Enhanced"] = "Enhanced",
            ["Player_PlayPauseTooltip"] = "Play / Pause (Space)",
            ["Player_RewindTooltip"] = "10s Rewind (←)",
            ["Player_ForwardTooltip"] = "10s Forward (→)",
            ["Player_SpeedTooltip"] = "Playback Speed",
            ["Player_MuteTooltip"] = "Mute / Unmute (M)",
            ["Player_PipTooltip"] = "PiP Mode (Shift+T)",
            ["Player_FullscreenTooltip"] = "Fullscreen (F)",
            ["Player_AudioSync"] = "Audio Synchronization",
            ["Player_AudioSyncReset"] = "Reset Audio Sync (0 ms)",
            ["Player_SubtitleSync"] = "Subtitle Synchronization",
            ["Player_SubtitleSyncReset"] = "Reset Sync (0 ms)",
            ["Player_AspectAuto"] = "Auto",
            ["Player_AspectOriginal"] = "Original",
            ["Player_Enhanced_Title"] = "ENHANCED",
            ["Player_Enhanced_Reset"] = "Reset",
            ["Player_ShaderTitle"] = "VIDEO ENHANCEMENT & SHADERS",
            ["Player_ShaderOff"] = "Off",
            ["Player_ShaderDesc"] = "Sharpens broadcast or scales to 4K using AMD FidelityFX algorithms.",
            ["Player_FastZapTitle"] = "LIVE TV CHANNEL SWITCHING",
            ["Player_FastZapUltra"] = "⚡ Ultra Fast (200ms)",
            ["Player_FastZapStd"] = "Standard (Stable)",
            ["Player_FastZapDesc"] = "Resets buffer on live TV switching to reduce channel start time to near instant.",
            ["Player_AudioEnhTitle"] = "SMART AUDIO PROCESSING",
            ["Player_AudioEnhOff"] = "Off",
            ["Player_AudioEnhLoudnorm"] = "EBU R128 Normalization",
            ["Player_AudioEnhNight"] = "Night Mode (Compressor)",
            ["Player_AudioEnhDesc"] = "Prevents volume spikes during channel switching or provides clear dialogue at night.",
            ["Player_HwTitle"] = "HARDWARE ACCELERATION",
            ["Player_HwDesc"] = "Uses your GPU for video decoding to drastically reduce CPU usage.",
            ["Player_DeintTitle"] = "DEINTERLACING",
            ["Player_DeintOn"] = "On",
            ["Player_DeintOff"] = "Off",
            ["Player_DeintDesc"] = "Removes scan lines in 1080i/576i broadcasts to convert video into smooth progressive frames.",
            ["Player_PresetTitle"] = "PICTURE PRESET",
            ["Player_PresetNatural"] = "Natural",
            ["Player_PresetVivid"] = "Vivid",
            ["Player_PresetSports"] = "Sports",
            ["Player_PresetCinema"] = "Cinema",
            ["Player_PresetCustom"] = "Custom",
            ["Player_EqualizerTitle"] = "FINE PICTURE TUNING",
            ["Player_Brightness"] = "Brightness",
            ["Player_Contrast"] = "Contrast",
            ["Player_Saturation"] = "Saturation",
            ["Player_Gamma"] = "Gamma",
            ["Player_EqReset"] = "Reset Picture Settings (0)",

            // Toasts
            ["Toast_RemovedFromResume"] = "'{0}' removed from continue watching.",
            ["Toast_AllHistoryCleared"] = "Watch history cleared.",
            ["Toast_SourceDeleted"] = "Source deleted.",
            ["Toast_CacheCleared"] = "Cache cleared.",
            ["Toast_AppReset"] = "All settings reset to defaults.",
            ["Toast_StartingOver"] = "Starting from beginning...",
            ["Toast_ResumingAt"] = "Resuming from {0}",
            ["Toast_AddedToFav"] = "Added to favorites",
            ["Toast_RemovedFromFav"] = "Removed from favorites",
            ["Toast_SeriesAddedToFav"] = "Series added to favorites",
            ["Toast_SeriesRemovedFromFav"] = "Series removed from favorites",
            ["Toast_SourceLoaded"] = "'{0}' source activated.",
            ["Toast_SourceLoading"] = "Loading '{0}'...",
            ["Toast_LangChanged"] = "Application language set to English.",
            ["Toast_ContentNotAvailableInSource"] = "This content is not available in the active source.",
            ["Toast_ContentNotInPlaylist"] = "This content is not currently in your playlist.",
            ["Toast_LoadDetailsError"] = "Could not load details."
        };

        public static string Get(string key)
        {
            var dict = CurrentLanguage == "en" ? _en : _tr;
            if (dict.TryGetValue(key, out var val)) return val;
            if (_tr.TryGetValue(key, out var trVal)) return trVal;
            return key;
        }

        public static string Get(string key, params object[] args)
        {
            string format = Get(key);
            try
            {
                return string.Format(format, args);
            }
            catch
            {
                return format;
            }
        }

        public static void SetLanguage(string lang)
        {
            CurrentLanguage = lang == "en" ? "en" : "tr";
            var dict = CurrentLanguage == "en" ? _en : _tr;

            if (Application.Current != null)
            {
                foreach (var kvp in dict)
                {
                    Application.Current.Resources[kvp.Key] = kvp.Value;
                }
            }

            LanguageChanged?.Invoke();
        }
    }
}
